---
name: Sub-Private
version: 0.01
author:
  - 'Peter Makholm <peter@makholm.net>'
abstract: Private subroutines and methods
license: perl
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/pmakholm/sub-private-perl/tree/master
requires:
  Attribute::Handlers: 0
  B::Hooks::EndOfScope: 0
  Sub::Identify: 0
  namespace::clean: 0
build_requires:
  Test::More: 0
  Test::NoWarnings: 0
provides:
  Sub::Private:
    file: lib/Sub/Private.pm
    version: 0.01
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
